### ISSUE TITLE
Fast js detection

### ISSUE THREAD

**Issue by ttttmr** [tdewolff/parse#101]
I use js.Parser to detect if some string is js code, but it's slow again for me

I tried using js.Lexer, but that doesn't seem to work, I'm getting regex parsing errors, see some related issues, like #72, regex seems very difficult to handle in Lexer

I would like to ask is there any way to simplify js.Parser to detect js and make it faster

```go
// works, but too slow
func JsDetect(body []byte) bool {
	_, err := js.Parse(parse.NewInputBytes(body), js.Options{})
	return err == nil
}
```

```go
// hope it works, but no
func JsDetect2(body []byte) bool {
	l := js.NewLexer(parse.NewInputBytes(body))
	for {
		tt, _ := l.Next()
		switch tt {
		case js.ErrorToken:
			if l.Err() != io.EOF {
				return false
			} else {
				return true
			}
		}
	}
}
```

**Comment by tdewolff** [comment]
Hi tmr,

Thank you for writing to me. As you can read in the issue, this is not a
problem of the lexer or parser, but rather a property of the JS language.
You cannot lex a JS source code without also parsing it. You can use a rule
that is 99% of the time correct (see the original JS parser, or the one
from Douglas Crockford (http://www.crockford.com/jsmin.html) , but if you
want to be 100% of the time correct you need to properly parse JS. What I
don't understand is when you refer to slow or fast, what has speed to do
with the issue?

Saludos cordiales,
Taco de Wolff
