### ISSUE TITLE
Questions about JS() method and String() method in js ast code

### ISSUE THREAD

**Issue by ttttmr** [tdewolff/parse#103]
As far as I see most of JS() and String() are different, String() contains some description characters etc.

https://github.com/tdewolff/parse/blob/2c5882a096909be935180223128ecf988a8c9494/js/ast.go#L990-L1004

Here n.Computed is interface(IExpr), should the JS() implementation use n.Computed.JS(), like this

```go
func (n PropertyName) JS() string {
	if n.Computed != nil {
		val := n.Computed.JS()
		if val[0] == '(' {
			return "[" + val[1:len(val)-1] + "]"
		}
		return "[" + val + "]"
	}
	return string(n.Literal.Data)
}
```

**Comment by ttttmr** [comment]
https://github.com/tdewolff/parse/blob/2c5882a096909be935180223128ecf988a8c9494/js/ast.go#L1053-L1072

There seems to be something strange here, the s variable is not returned, and the data of n.Key seems to be lost

**Comment by ttttmr** [comment]
https://github.com/tdewolff/parse/blob/2c5882a096909be935180223128ecf988a8c9494/js/ast.go#L1887-L1900

Here the JS() method calls n.X.String(), should we use n.X.JS()

**Comment by tdewolff** [comment]
Valid remarks, I've incorporated the fixes!
