### ISSUE TITLE
Convert back to string syntax error after js parse

### ISSUE THREAD

**Issue by ttttmr** [tdewolff/parse#112]
Here is the test code

```js
function i(t){return e*H(- --t)*Math.sin((r-t)/n)}
```

convert string after parse

```js
function i (t) { return e * H(---t) * Math.sin((r - t) / n); };
```

<img width="721" alt="image" src="https://github.com/tdewolff/parse/assets/32825326/41b19fbb-bfbf-4a56-a4cb-c3bb3981e3d8">

https://go.dev/play/p/JtsMAg5NW26

**Comment by tdewolff** [comment]
Thanks, should be fixed now!
