### ISSUE TITLE
Adding custom tokens to lexer?

### ISSUE THREAD

**Issue by jimafisk** [tdewolff/parse#113]
Is it possible for users to extend the HTML5 lexer to handle custom tokens? 

Just wondering if it would make sense to import this project as a base for create a custom templating language with control structures like `if` statements, `for` loops, and variables. For example:

```html
{if myVar}
  <h1>{myVar}</h1>
{/if}
```

Where `{myVar}` could get evaluated instead of being seen as a `TextToken`. My apologies if that's not really the intended use case for this project! Thank you!

**Comment by tdewolff** [comment]
Yes you can fork the HTML lexer and easily add your own tokens, it's not a very difficult tokenizer. It's not the intention of this HTML parser to include that functionality.

But why don't you parse the output of this HTML parser, and evaluate the TextTokens?

**Comment by jimafisk** [comment]
Ok gotcha, so there's not an API for extending tokens but I could fork the project and add it.

Great suggestion, it seems like parsing the `TextToken` output for specific syntax would be the way to go! Thank you!
