### ISSUE TITLE
TestParseDecimal/5.1 no longer passes

### ISSUE THREAD

**Issue by QuLogic** [tdewolff/parse#115]
This is probably dependent on architecture in some way, or floating-point optimizations. I am running on a now somewhat older x86_64 though, so it's not too esoteric.
```
--- FAIL: TestParseDecimal (0.00s)
    --- FAIL: TestParseDecimal/5.1 (0.00s)
    decimal_test.go:26: 5.1000000000000005 != 5.1
```
This occurs with the older `github.com/tdewolff/test` 1.0.9 that had absolute comparisons, or with the newer 1.0.10 that has relative comparisons.

**Comment by tdewolff** [comment]
Thanks for the report. Can't figure out what's wrong here, with `Epsilon = 1e-10`:

Absolute: `5.1000000000000005 - 5.1 = 5e-16 < 1e-10`

Relative: `(5.1000000000000005 - 5.1) / 5.1 ≈ 1e-16 < 1e-10`

For both cases the test should pass (as it does on my computer), not sure what is wrong...

**Comment by tdewolff** [comment]
Pushed out a change in the test package, maybe that fixes it?

**Comment by QuLogic** [comment]
Thanks, it looks like 2.7.1 works, and I didn't need to use the intermediate commit of the `test` package.
