### ISSUE TITLE
JS package: mystified.. how can my `IVisitor` impl possibly be `nil` in its `Enter` method?!

### ISSUE THREAD

**Issue by metaleap** [tdewolff/parse#119]
First off, fantastic project! Was so glad when I found this and all the JS parsing worked right away!

Well, this issue I'm having now, though, is a total mindbender to me right now..

First let me refresh you that your `js` package's `func Walk(v IVisitor, n INode)` has only this one call to `IVisitor.Enter` and there is no other anywhere:

```go
	if v = v.Enter(n); v == nil {
		return
	}
```

My `IVisitor` looks like this:

```go
type jsWholeASTRewriter struct {
	gatherMode  bool
	err      error
	rewrites map[js.INode]js.INode
}

func (*jsWholeASTRewriter) Exit(js.INode) {}

func (me *jsWholeASTRewriter) Enter(node js.INode) js.IVisitor {
	if me.gatherMode {
		me.gather(node) // writes to me.err if any error encountered
	} else {
		me.rewrite(node) // writes to me.err if any error encountered
	}
	return ıf(me.err == nil, me, nil) // ıf is just a custom terniary-op helper func
}
```

And [here's](https://github.com/metaleap/zui/blob/05d7addaa522293585766e9f3be9755357bdd093/js.go#L84) how I call `js.Walk`.

Now with error-free JS inputs, it all works as expected, but when feeding error-provoking JS, [this first line](https://github.com/metaleap/zui/blob/05d7addaa522293585766e9f3be9755357bdd093/js.go#L108) in `Enter` panics with `nil-pointer dereference`.

But from the `js.Walk` code, I just don't get how it could ever be the case.

Any ideas? Maybe it's just late and I'm not seeing the obvious  :grin:

**Comment by metaleap** [comment]
I got it. Had to force the return type of the generic `ıf` call to `js.IVisitor`, otherwise it'd be auto-inferred to `*jsWholeASTRewriter`. So changing the last line in `Enter` to `return ıf[js.IVisitor](me.err == nil, me, nil)` did the trick.

Nothing beats a fresh morning! :coffee:

**Comment by tdewolff** [comment]
Believe me, it is a bad idea to work late at night. Usually the next morning you have to rewrite it all! Happy to see you figured it out ;-)
