### ISSUE TITLE
CSS package readme is out of date

### ISSUE THREAD

**Issue by variadico** [tdewolff/parse#12]
https://github.com/tdewolff/parse/blob/master/css/README.md

I'm looking at `stylesheet, err := css.Parse(r)` and I don't see `Parse` in css/parse.go. I see `NewParser` though. Also, `[]Nodes` doesn't seem to exist anymore, so `for _, node := range stylesheet.Nodes` doesn't work.

Just making sure it's not only me.

**Comment by variadico** [comment]
Found the godoc examples.

**Comment by tdewolff** [comment]
Yes, this was the old interface which I changed to a more light-weight alternative that was faster.
