### ISSUE TITLE
error parse js ?

### ISSUE THREAD

**Issue by qokelate** [tdewolff/parse#120]
```
import (
	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/parse/v2/js"
)

...

	l := js.NewLexer(parse.NewInput(strings.NewReader(`a.replace(/^\.\/(.*)\.\w+$/,"$1")`)))
	for {
		tt, text := l.Next()

		switch tt {
		case js.ErrorToken:
			if l.Err() != io.EOF {
				// fmt.Println("Error on line", ":", l.Err())
				log.Errorln(l.Err())
			}
			break
		case js.IdentifierToken:
			// fmt.Println("Identifier", string(text))
		case js.NumericToken:
			// fmt.Println("Numeric", string(text))
			// ...
		case js.StringToken:
			fmt.Println("string", string(text))
		}

	}
```

```
ERROR unexpected \ on line 1 and column 13
    1: a.replace(/^\.\/(.*)\.\w+$/,"$1")
```

**Comment by tdewolff** [comment]
The JS lexical specification is not context independent unfortunately. This means you can't just "lex" a JS source file, you can only parse it. The parser keeps track of contexts where a regular expression is allowed, and reparses the stream in those cases using https://pkg.go.dev/github.com/tdewolff/parse/v2@v2.7.14/js#Lexer.RegExp. You'll need to do the same if you which to only "lex" JS and not parse it. This is a limit of the JS language, not of this package.
