### ISSUE TITLE
JS: distinguish regexps from division correctly

### ISSUE THREAD

**Issue by RReverser** [tdewolff/parse#16]
Hello, good work on the minification / parsing libs.

There is an issue with lexing though. Those are rare cases, but they're still valid JavaScript. In JS lexer, you can't go away with one-token lookbehind to figure out whether `/` is a beginning of a regular expression or a division (in fact, this is what Crockford did wrong in JSMin / JSLint and many other implementations copied those bugs instead of following the spec).

Just few examples:

``` javascript
(a+b)/42/i  // <-- divide (a+b) by 42 and by i
if(a+b)/42/i  // <-- regular expression /42/i

function foo() {} /42/i  // <-- function declaration followed by a regex
var foo = function foo() {} /42/i  // <-- function expression divided by 42 and i

{console.log('a');} /42/i  // <-- block statement followed by a regex
({ valueOf: () => 100 }/42/i)  // <-- object expression divided by 42 and i

/* ... */
```

**Comment by tdewolff** [comment]
Yeah I was afraid of that. Apparently it works for 99% of the  cases, but you're right, it should be fixed. I have more plans for JS in the future, mainly building a proper parser. That would fix this issue as well.

Thanks for notifying! Although nothing I can do to fix this anytime soon..
