### ISSUE TITLE
Tags are breaking dep, the official golang dep tool

### ISSUE THREAD

**Issue by mikegleasonjr** [tdewolff/parse#18]
Hi !

Latest tag is v2.0.0 which is almost a year old.

I am now using `dep` (official golang dep tool) and when I import `minify` in one of my project before running...

```
dep init
dep ensure -update
```

It breaks with...

```
vendor/github.com/tdewolff/minify/html/html.go:194: undefined: html.Template
```

This is because with `dep` we can only specify versions of direct dependencies (`minify` in this case). We can't specify indirect dependencies versions (can't specify master for `parse` in this case). So the code goes out of sync.

Can you release tags for all the dependencies of the latest version of `minify`?

Thanks!

**Comment by mikegleasonjr** [comment]
see second comment here:
https://github.com/golang/dep/issues/302

**Comment by tdewolff** [comment]
I've released a new version, is this now fixed?

**Comment by mikegleasonjr** [comment]
Yup everything is fine now thanks!
