### ISSUE TITLE
CSS: Custom Properties / Variables support

### ISSUE THREAD

**Issue by pdf** [tdewolff/parse#19]
Would be nice to see [css-variables](https://www.w3.org/TR/css-variables-1/) parsed successfully, currently encountering a variable declaration results in `ErrBadDeclaration`.

**Comment by tdewolff** [comment]
Ah yes, someone else had the same problem, but according to the specs this is invalid. I see that this is a candidate recommendation, I can see supporting that. I will implement this soon.

**Comment by tdewolff** [comment]
This is fixed in 91bb7a0b8e964af35c919fa0d67c957a093d552d

**Comment by pdf** [comment]
Wow, super-fast turn-around, thank you!
