### ISSUE TITLE
doco bug: example wrong for css parser

### ISSUE THREAD

**Issue by client9** [tdewolff/parse#22]
Hello!

great project!

 I found a doco bug here at https://github.com/tdewolff/parse/blob/master/css/README.md#examples-1

it says:

```go
func main() {
	// false because this is the content of an inline style attribute
	p := css.NewParser(bytes.NewBufferString("color: red;"), false)
```

The `false` should be `true` since it's inline.  It's just prints nothing as it current is.

See:
https://github.com/tdewolff/parse/blob/master/css/parse.go#L95

regards

nickg

**Comment by tdewolff** [comment]
Thanks! It was changed from `isStylesheet` to `isInline` I think some time ago, never updated the readme...

**Comment by client9** [comment]
bam!  that was fast.  I'm sure I'll send in some other notes/PR/etc as I keep digging.
