### ISSUE TITLE
feature request: expose line number

### ISSUE THREAD

**Issue by client9** [tdewolff/parse#23]
Hi there,  

I'm using the parser to check validity of something and I'd like to know where an issue occurred.

Let's use the CSS parser as an example.  (This is the Lexer, but the line count could be exposed in the parser as well).

Looks like the area would be in here:

```
// Next returns the next Token. It returns ErrorToken when an error was encountered. Using Err() one can retrieve the error message.
func (l *Lexer) Next() (TokenType, []byte) {
	switch l.r.Peek(0) {
	case ' ', '\t', '\n', '\r', '\f':
		l.r.Move(1)
		for l.consumeWhitespace() {
		}
		return WhitespaceToken, l.r.Shift()
```

It would seem the lever could keep a `lineNum int` and increment here (maybe with changes to "consumeWhitespace" as well).

thoughts?

regards,

n

**Comment by tdewolff** [comment]
This was originally in the design, but it was left out over parsing speed. Since for the minifier library this was not essential, I removed it. I agree that it would be a handy feature for the parsing library and it could be a good idea to add it in the future. I don't have a lot of time, so not any time soon for me though...

**Comment by client9** [comment]
I hear ya brother... no problem.  I may or may not get to it myself.  Thanks anyways!

**Comment by tdewolff** [comment]
This could be implemented as a separate pass, as mentioned in the last section of http://nothings.org/computer/lexing.html.

**Comment by tdewolff** [comment]
It's implemented now in `position.go` and `error.go`. Upon a parsing error, an error of type `*parse.Error` is returned, containing `Line`, `Col`, `Context` (the content of bad line) and the error in `Message`.
