### ISSUE TITLE
cannot find package "github.com/tdewolff/parse/v2/buffer"

### ISSUE THREAD

**Issue by apisit** [tdewolff/parse#43]
I'm upgrading `minify` to the latest one but seems like it uses `github.com/tdewolff/parse/v2/buffer` which doesn't exist in the repo.

any solution how to solve this? 

Thanks

**Comment by brentmn** [comment]
The semantic import versioning of local imports looks to be forcing adoption of modules if we rely on master. I'm working around this by checking out specific commits for `minify` and `parse` repos on my local and build systems.

**Comment by tdewolff** [comment]
@apisit Yes, it is because we have switched to using Go modules. It was my impression that older Go versions were equipped to deal with the new import path syntax?

**Comment by tdewolff** [comment]
@apisit Actually...have you upgraded `github.com/tdewolff/parse` to the latest as well? Go versions 1.9, 1.10 and 1.11 should be able to parse the new import paths (with `/v2/`) properly and you should have no issues. Using Go modules in the future however will automatically update the `parse` library alongside `minify`. In any case, locally with `GO111MODULE=off` the new versions seem to work fine on go1.11.

**Comment by tdewolff** [comment]
See https://github.com/tdewolff/minify/issues/232

If you cannot upgrade to Go 1.9.7+, 1.10.3+ or 1.11, then please DOWNGRADE to minify@v2.3.6 and parse@v2.3.4. If you ARE using those newer Go versions, please UPGRADE to the latest versions.

**Comment by JayneJacobs** [comment]
I am using go version go1.11.5 darwin/amd64 and still have this issue.

**Comment by JayneJacobs** [comment]
This did work 
minify -  git checkout tags/v2.3.6
  cd ../parse
  git checkout tags/v2.3.4

**Comment by spaceblock** [comment]
> This did work
> minify - git checkout tags/v2.3.6
> cd ../parse
> git checkout tags/v2.3.4

error: pathspec 'tags/v2.3.4' did not match any file(s) known to git
