### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shiyuleixia** [tdewolff/parse#45]
Hello,I wonder where's the "v2" directory?  I just built the package ,and there's an error such as this:
root@default:/go/src/github.com/tdewolff/parse# go build
error.go:7:2: cannot find package "github.com/tdewolff/parse/v2/buffer" in any of:
        /usr/local/go/src/github.com/tdewolff/parse/v2/buffer (from $GOROOT)
        /go/src/github.com/tdewolff/parse/v2/buffer (from $GOPATH)

and then I tried to pull the v2 directory with git,but there's another error:
package github.com/tdewolff/parse/v2: cannot find package "github.com/tdewolff/parse/v2" in any of:
        /usr/local/go/src/github.com/tdewolff/parse/v2 (from $GOROOT)
        /go/src/github.com/tdewolff/parse/v2 (from $GOPATH)

How can I fix this error?

**Comment by tdewolff** [comment]
Hi @shiyuleixia, this is because this package has switched to using the new Go modules feature (dependency management). You will need to use a relatively new Go version (go1.9.7+, go1.10.3+, go1.11), which will fix this.

If this is not possible, pin the `github.com/tdewolff/parse` version to v2.3.4. Let me know if that works for you.

**Comment by vision8tech** [comment]
I can confirm that `go build` works without a problem.
In my case, `go version` reports `go version go1.11.2 darwin/amd64`.

**Comment by vision8tech** [comment]
@tdewolff Hi Taco, btw what do you mean with the statement "pin to parse@v2.3.4"?

While playing with Isomorphic Go, I got into a problem related to the fact that currently GopherJS does not support modules yet. So what I did and solved the problem - as per your advice - was to install  `github.com/tdewolff/minify` version 2.3.6 and  `github.com/tdewolff/parse` version 2.3.4.
And used the following approach:
```shell
$ cd ${GOPATH}/github.com/tdewolff
$ curl -L https://github.com/tdewolff/minify/archive/v2.3.6.zip --output minify-2.3.6.zip
$ unzip minify-2.3.6.zip
$ mv minify-2.3.6 minify
```
So, that is what you actually mean by "pin to parse@v2.3.4"?

Thanks

**Comment by tdewolff** [comment]
I mean that you need to use version `v2.3.4` for the package `parse` as well as version `v2.3.6` for package `minify`, which is called pinning when using a dependency manager. The way you approached it should work fine, let me know if it causes any problems.

**Comment by vision8tech** [comment]
@tdewolff Yes, it worked that way. Thanks for the confirmation. 👍
