### ISSUE TITLE
[Xml Parser] recieved nil when calling lexer.Text() on TextToken

### ISSUE THREAD

**Issue by YafimK** [tdewolff/parse#50]
Reproduce with simple xml - 

`<?xml version="1.0"?>\r\t\n<session id="12345" user="1$2d#"><!DOCTYPE note>DUCK</xml>`
when the parser reaches "DUCK" - calling lexer.Text() will return nil.

After short investigation - it might be since the text buffer is not being updated whenever TextToken is returned.

Is it intentional? i.e. feature not bug :)?

**Comment by tdewolff** [comment]
`Text()` would return the textual representation of tags and attribute values, leaving out surrounding delimiters. For example the sessions tag would return a `StartTag` with bytes `<session`, in this case `Text()` would return just `session`. For attributes it would return the name of the attribute. In the case of a `Text` token, the returned bytes already represent the "textual" version of the token, so `Text()` is not populated.

I agree this is somewhat counterintuitive to the name. Perhaps `Text()` should be renamed to `Name()`?

**Comment by YafimK** [comment]
Sounds great! - but won't it break API? we could also leave the text and add the capability to get the text of text tokens and etc after uncapping and etc. (I've re implemented these in my code but i feel it's better to be in this great libary)

**Comment by tdewolff** [comment]
I will have to come back to you at a later time, I am very busy right now, sorry!
