### ISSUE TITLE
Make the parser streaming

### ISSUE THREAD

**Issue by JAicewizard** [tdewolff/parse#59]
The use-case for this package is often big files that need more performance than the non-lexing alternatives.
The current implementation reads the full file at once, which is not ideal for this situation.

**Comment by wade-welles** [comment]
I require this functionality too, so I will be working on it, and notify you when it is complete (if it is completed before someone else beats me too it of course).

**Comment by tdewolff** [comment]
There is the old implementation of the https://github.com/tdewolff/parse/blob/master/buffer/streamlexer.go which did exactly that. It should be modified a bit to include in the latest release I suppose.

In general, the use-case that was more prevailing as I saw, was that people already had loaded their files into memory thus making the stream lexer not necessary. Given that most files are several MBs at most, and given that loading the file entirely was much faster, I opted for the fastest method.

I suppose a use-case could be loading large JSON or XML files which is a valid use case. I want the parsers to accept either the regular or the streaming lexers, should be little work.

**Comment by JAicewizard** [comment]
I don't need this as a requirement, but I am working with not that large files, but i noticed that there was a large allocation from NewLexer and thought that was weird.
A lexer is perfect for streaming, I would do it if I had more time but I am really busy atm.

**Comment by tdewolff** [comment]
Upon further research, the streaming lexer could be pretty much swapped into place but would require referring to the lexer using an interface instead of a direct pointer. Being a hot path in all parsers/minifiers, I need to evaluate the cost-benefit of this...
