### ISSUE TITLE
First selector in media query sometimes parsed incorrectly.

### ISSUE THREAD

**Issue by jimmyfrasche** [tdewolff/parse#6]
```
@media print {
    .class {
         width: calc(10% - 5rem);
    }
}
```

is being parsed as:
(extraneous elements omitted, some declarations simplified for presentation)

```
&AtRuleNode{
    Block: &BlockNode{
         Nodes: []Node{
              {&TokenNode{Delim, "."}}, //should be in RuleSetNode below
              {&RuleSetNode{/*yada yada*/}},
         },
    },
}
```
instead of the "." going in the ruleset node. This also happens with ``[class]`` but not ``#id``.

Looking at ``parseBlock``, I would guess that ``parseAtRule`` isn't unshifting the first token appropriately in all cases, though I have not verified this.

**Comment by tdewolff** [comment]
Good find. The CSS parse spec is really fuzzy about this. I am suspecting that more combinations of brackets inside functions (or in other spots) might still break the parser, because the spec is unclear about brackets in general I find.
