### ISSUE TITLE
Question about structure

### ISSUE THREAD

**Issue by wade-welles** [tdewolff/parse#60]
Forgive me if this is a bit to esoteric; so much so that it may not be useful discussion. 

But I noticed that you have two calls in each of your formats [js, json, css, html, ..] 

To `parse` package and `buffer` package. 

However adding 

```
type Lexer struct {
	r *buffer.Lexer
}
```

To the parse library appears to make it so all the format libraries need only a single import call to parse. And in most cases I would say it is better to allow interdependent access to the different parts of the library is best, but I don't see these being used separately. And `parse.Lexer` reads better than `buffer.Lexer`. 

I can create a pull request showing exactly what I mean and you can decide if you think its worthwhile or not. Or you can close this topic, no hard feelings. 

Thanks for the library. I have been working with parse/lexing more since I have decided to implement a full MRI Ruby in Go, and this has been helpful along with other resources in really understanding the process of parsing and lexing. 

I noticed you have a stream lexer, but parsing does not appear to have the same functionality. As just practice, I can issue a pull request on that if you are interested.

**Comment by tdewolff** [comment]
Thanks for the interest! I'm not exactly following what you mean, but I can tell you you're probably right. There is a little package refactoring that could be done, if you show a proposal that would be great.

As I said in the other issue, the streaming lexer is from an older version of `parse`, and should be relatively simple to adapt to the new functionality. Crucially, the new parse version needs `0x00` at the end of the buffer to indicate its end. This is quite a fast way of checking when to read in a new chunk/check EOF. I will look into this but this might take a little while.

FYI: I'm working on a full-featured JavaScript minifier and have all but completed the JS parser, check the `develop` branch as it may help you if you need to build up an AST for MRI Ruby?
