### ISSUE TITLE
xml.NewLexer changed API breaks tdewolff/canvas from compiling when Go finds newer dependencies

### ISSUE THREAD

**Issue by zzwx** [tdewolff/parse#65]
I'm not a big expert on how Go modules select dependencies, I'm only suspecting that this due to both `tdewolff/canvas` and `tdewolff/parse/v2` being used in one project through other modules.

The compiler issues an error:
```
github.com/tdewolff/canvas
../canvas/latex.go:80:19: cannot use r (type *os.File) as type *parse.Input in argument to xml.NewLexer
```

I assume this is due to the diamond dependency problem (or whatever it's called), when compiler chooses a newer version for the build out of available options.

In this case it's attempting to choose `xml.NewLexer` version that is accepting a newer API `*parse.Input` argument, vs older API's `io.Reader`, although `github.com/tdewolff/parse/v2 v2.4.3` is requested in canvas's `go.mod`.

I don't see a solution to this other than to patch `github.com/tdewolff/canvas`, I just did a quick test and it seems working (https://github.com/zzwx-forks/canvas/commit/e51fdb968782f1340ee69948d0797e19e4aa754b)

**Comment by tdewolff** [comment]
Yes, the parse library should've really pushed out a new version. Thanks for bringing this to attention, should be fixed!

**Comment by tdewolff** [comment]
Fixed in https://github.com/tdewolff/canvas/commit/dca56fb323bb5849e6dcf7997e31d8b846f4dd3e

**Comment by zzwx** [comment]
Seems to fix the issue, thanks!
