### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [tdewolff/parse#66]
I could make the following work

> 	// true because this is the content of an inline style attribute
>	p := css.NewParser(bytes.NewBufferString("color: red;"), true)

by importing additionally
`"github.com/tdewolff/parse/v2"`

And replacing `bytes.NewBufferString("color: red;")` by

`parse.NewInput(bytes.NewBufferString(minimalStyleSheet))`

Thank you for this useful package, Stephan

**Comment by tdewolff** [comment]
Thanks!
