### ISSUE TITLE
err:identifier  n has already been declared 

### ISSUE THREAD

**Issue by fzxs8** [tdewolff/parse#69]
使用 下面的代码执行获取AST会出现错误.

golang 代码:
```golang
	ast, err := js.Parse(parse.NewInputBytes(jsStr))

```
JavaScript代码
```JavaScript
const n = 100


let fi = [1, 2, 3, 4], r = []
for (let t = 0, n = fi.length; t < n; t++) {
    const n = fi[t];
    r.push(`${n}:${n + 1};`)
}
// if (n > 0) {
//     const n = 200;
//     r.push(`${n}:${n + 1};`)
// }
console.info(r)
```

出现了错误 
> err:identifier n has already been declared on line 6 and column 11
    6:     const n = fi[t];

**Comment by tdewolff** [comment]
Thanks! There were a couple of bugs related to for initializers, they've all been fixed!

**Comment by fzxs8** [comment]
> Thanks! There were a couple of bugs related to for initializers, they've all been fixed!

Hard work!
