### ISSUE TITLE
AST does not model CSS functions correctly

### ISSUE THREAD

**Issue by jimmyfrasche** [tdewolff/parse#7]
The AST cannot model a function with whitespace-delimited arguments.

Some examples are calc, "to left top" in linear-gradient, or something like ``attr(data-length px)``. 

There needs to be an extra level like Args for comma-delimited arguments, each of which is a slice of white-space delimited tokens, so that ``attr(id)`` would be something like ``[]CD{[]WD{"id"}}`` and ``linear-gradient(to left top, black)`` would be
```
[]CD{
    []WD{"to", "left", "top"},
    []WD{"black"},
}
```

I'm not 100% sure that would cover all cases, but it would handle all the ones I can think of, at least.

**Comment by tdewolff** [comment]
Good find. The CSS parse spec is really fuzzy about this. I am suspecting that more combinations of brackets inside functions (or in other spots) might still break the parser, because the spec is unclear about brackets in general I find.

**Comment by jimmyfrasche** [comment]
This is almost correct. Unfortunately some (though not all) of the whitespace is signficant

You can do ``calc(100%/2)`` or ``calc(100%/2 - 1em)`` but not ``calc(100%/2-1em)`` or ``calc(50%-1em)``

**Comment by jimmyfrasche** [comment]
Also something like ``linear-gradient(to right, black, white)`` is not the same as ``linear-gradient(toright, black, white)``

**Comment by tdewolff** [comment]
I've added a temporary fix but I need to work on adhering the CSS spec better, until then this commit won't break the CSS I hope!
