### ISSUE TITLE
err:expected  instead of get in method definition

### ISSUE THREAD

**Issue by fzxs8** [tdewolff/parse#70]
你好!
下面的代码获取AST出现错误

```JavaScript
class Rectangle {

    // userName   TODO ERROR

    // constructor
    constructor(height, width) {
        this.height = height;
        this.width = width;

        this.userName = "hello"
    }

    userName // TODO ERROR

    // Getter
    get area() {
        return this.calcArea()
    }

    // Method
    calcArea() {
        return this.height * this.width;
    }
}

```

golang 代码
```golang
	jsStr, err := ioutil.ReadFile("./testfile/class.js")

	if err != nil {
		fmt.Printf("ERROR %s", err)
	}

	ast, err := js.Parse(parse.NewInputBytes(jsStr))
```
出现错误:

> err:expected ( instead of get in method definition on line 19 and column 5
   19:     get area() {
           ^/nast:Decl(class Rectangle Method(constructor Params(Binding(height), Binding(width)) Stmt({ Stmt((this.height)=height) Stmt((this.width)=width) Stmt((this.userName)="hello") })) Method(userName Params() Stmt({ })))

**Comment by fzxs8** [comment]
对不起, 这共有属性定义方式是一个实验性功能..
您的代码是没有问题的.

**Comment by tdewolff** [comment]
Yes, thanks for the issue anyways. This is indeed a proposed feature not yet incorporated in the specification, see https://tc39.es/proposal-class-fields/ for the draft. I suggest we wait till it gets accepted before adding it.

**Comment by tdewolff** [comment]
Moved to https://github.com/tdewolff/minify/issues/412
