### ISSUE TITLE
JS: tokenizing regular expressions

### ISSUE THREAD

**Issue by karelorigin** [tdewolff/parse#72]
I noticed that properly tokenizing JS regular expressions are left up to the user with `(*Lexer).RegExp()`. This makes things difficult as there's no easy way to differentiate between a legit DivToken/DivEqToken and a regexp. 

I'm trying to rewrite some key identifiers while tokenizing and keeping the JS itself intact. As far as I know, this isn't possible to do with ASTs, since they cannot be converted back to valid JS.

I tried storing previous tokens and checked whether they would create a context where regular expressions can exist. 

For example:

```js
1/2/3
```

The first DivEqToken would not start a new regexp as `1` is not a valid delimiter. Same goes for 

```js
(1)/2/3
```

This actually works in most cases. However, it gets more complicated with inline if statements and for loops:

```js
// perfectly valid JavaScript and RegExp
if(true) /x/
```

Hopefully, I made my issue and intentions clear :)

Thanks!

**Comment by tdewolff** [comment]
Yes! This is actually a really difficult subject, because the a JS lexer is not context-free unfortunately. Depending on the context we can expect a regular expression instead of a division.

What I do in the parser at https://github.com/tdewolff/parse/blob/master/js/parse.go#L1506 is that whenever we expect an expression (due to the context), but the first token we see is a `/` or `/=`, then go back to the lexer and re-read that as a regular expression. This is impossible to do without the parser, as the lexer isn't aware of the context. I don't think there is an easy way to solve this unfortunately... :-(

**Comment by karelorigin** [comment]
Unfortunately, I think you might be right :(

Though if I remember correctly, the older version of the tokenizer did tokenize them as regular expressions instead of DivTokens. What was the reason for that? Or was it just not following the JavaScript specs?

I guess the only alternative would be to fork the parser from this repo and make the required changes which would be a big pain due to the many pitfalls.

**Comment by tdewolff** [comment]
The previous lexer/parser was really much more basic and used a simple rule for context guessing, which I'm not sure is 100% accurate. Here an example: https://github.com/tdewolff/parse/blob/b6a6a8fd3edcd1e72e45e34ceb5ca204de4bea97/js/lex.go#L194. In particular, we check if we're in an expression state (after certain characters) which works 99% of the time (I think I remember a case where it didn't work well, but was archaic syntax anyways). You could follow something similar as in the link above.

**Comment by karelorigin** [comment]
Thanks! This issue has been keeping me from making actual progress for almost a week now, incredibly frustrating. I guess I'll just have to code something to help me keep track of different states like the link you gave me.

**Comment by karelorigin** [comment]
Interestingly enough you can see that this appears to be an issue everywhere, even in Chrome:
![image](https://user-images.githubusercontent.com/20503272/116139057-e4b14600-a6d5-11eb-86b5-40982a81a906.png)

 (note the lack of syntax highlighting on the regexp)

Almost ridiculous that it has to be this way, but perhaps that's just my annoyances getting to me. :P

**Comment by tdewolff** [comment]
Haha man this bit me a while back as well. It really is a big shame because it makes the lexer dependent on the parser, this is usually a strong code smell. This was one of the reasons to build the JS parser actually...which was so much more work than I had hoped.
