### ISSUE TITLE
PropertyName quoting

### ISSUE THREAD

**Issue by 89z** [tdewolff/parse#79]
Using this program:

~~~go
package main

import (
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

func main() {
   ast, err := js.Parse(parse.NewInputString(`y={"year":2021}`))
   if err != nil {
      panic(err)
   }
   for _, is := range ast.BlockStmt.List {
      oe := is.(*js.ExprStmt).Value.(*js.BinaryExpr).Y.(*js.ObjectExpr)
      for _, p := range oe.List {
         fmt.Println(p.Name.Computed)
         fmt.Println(p.Name.Literal)
         fmt.Println(p.Name.Literal.JS())
      }
   }
}
~~~

I get this result:

~~~
<nil>
year
year
~~~

So it appears that even though the key is quoted in the input, the quotes are stripped in the output, with no option to keep them. My use case is similar to above, where the value is valid JSON, so I would like the extract the JSON value and parse it as such. However that only works if the keys maintain quoting. I seems its possible with the tokenizer, does the Parser have some method?

**Comment by 89z** [comment]
Looks like you can use `Walk` to append quotes as needed:

~~~go
package main

import (
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
   "strconv"
)

type walker struct{}

func (w walker) Enter(n js.INode) js.IVisitor {
   switch n := n.(type) {
   case *js.PropertyName:
      s := string(n.Literal.Data)
      n.Literal.Data = strconv.AppendQuote(nil, s)
   }
   return w
}

func (walker) Exit(n js.INode) {}

func main() {
   ast, err := js.Parse(parse.NewInputString(`y={"year":2021}`))
   if err != nil {
      panic(err)
   }
   for _, stmt := range ast.BlockStmt.List {
      var w walker
      js.Walk(w, stmt)
      fmt.Println(stmt)
   }
}
~~~

somewhat awkward, but it works:

~~~
Stmt(y={"year": 2021})
~~~

**Comment by 89z** [comment]
Looks like you can use `Walk` to append quotes as needed:

~~~go
package main

import (
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
   "strconv"
)

type quote struct{}

func (q quote) Enter(n js.INode) js.IVisitor {
   pName, ok := n.(*js.PropertyName)
   if ok {
      s := string(pName.Literal.Data)
      pName.Literal.Data = strconv.AppendQuote(nil, s)
   }
   return q
}

func (quote) Exit(js.INode) {}

func main() {
   ast, err := js.Parse(parse.NewInputString(`y={"year":2021}`))
   if err != nil {
      panic(err)
   }
   for _, iStmt := range ast.BlockStmt.List {
      var q quote
      js.Walk(q, iStmt)
      fmt.Println(iStmt)
   }
}
~~~

somewhat awkward, but it works:

~~~
Stmt(y={"year": 2021})
~~~

**Comment by tdewolff** [comment]
This is probably a bug in `PropertyName.JS()`, @karelorigin  can you take a look please? I would expect `JS()` to output quotes when the LiteralExpr is a string.

**Comment by 89z** [comment]
Yeah, looks like they both currently just do the same thing:

https://github.com/tdewolff/parse/blob/50e07f9a3549c05468b023b36506d6c8c131ed08/js/ast.go#L987-L990

not a huge deal, as I found a workaround, but changing JS to add or maintain double quotes might be a good option

**Comment by karelorigin** [comment]
Hi @tdewolff and @89z, the purpose of the `JS` method is to recreate a valid JavaScript representation of the AST, not an exact one. 

However, I did take a look at what the cause of this behavior might be, as it can create issues with property names that are invalid when not encapsulated by quotes: `{"1a": 1}` vs `{1a: 1}`.  It would not make sense for the parser to correctly stringify these situations by default as they are only relevant when working with actual code (like we are doing right now). Surprisingly enough, it actually handles these cases exactly as it should:

```javascript
x = {"1a": 2}; 
// translates to (via `JS` method):
x = {"1a": 2}; 
```

Still though, it's probably a good idea to add an additional test to make sure that this does not break in the future. I can probably whip up a quick PR for that.

You may have noticed that the property name **was** encapsulated by quotes here. This happened because the parser's tokenizer parses `1a` as an actual `StringToken` (which contains quotes by default) rather than an `IdentifierToken` for property names such as `year`. This is something that will have to be changed at parser level instead @tdewolff. Changing the `(PropertyName).JS` method to compensate for this isn't a very good solution as it does not solve the underlying problem.

In the meantime @89z, I've created this Go snippet, that as far as I can tell, does exactly what you need:

```golang
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/parse/v2/js"
)

// visitor is a AST visitor and collects all object expressions
type visitor struct {
	objects []*js.ObjectExpr
}

func (v *visitor) Enter(n js.INode) js.IVisitor {
	switch n := n.(type) {
	case *js.ObjectExpr:
		v.objects = append(v.objects, n)
	default:
		return v
	}

	// Automatically skip any nested nodes as we
	// already found our object expression
	return nil
}

func (v *visitor) Exit(n js.INode) {}

// decoder is a JSON decoder that turns an object expression node into valid JSON
type decoder struct{}

// Decode decodes an object expression
func (d *decoder) Decode(o *js.ObjectExpr, out interface{}) error {
	js.Walk(d, o)

	// Unmarshal raw bytes into interface
	if err := json.Unmarshal([]byte(o.JS()), &out); err != nil {
		return err
	}

	return nil
}

func (d *decoder) Enter(n js.INode) js.IVisitor {
	v, ok := n.(*js.PropertyName)
	if !ok {
		return d
	}

	// Only encapsulate property names that do not include quotes by default (anything but js.StringToken)
	if v.Literal.TokenType != js.StringToken {
		v.Literal.Data = []byte("\"" + n.JS() + "\"")
	}

	return d
}

func (d *decoder) Exit(n js.INode) {}

func main() {
	ast, err := js.Parse(parse.NewInputString(`y = {"year": 2021};`))
	if err != nil {
		log.Fatal(err)
	}

	// Collect all object expressions from our JS code
	v := &visitor{}
	js.Walk(v, ast)

	// Skip if there weren't any object literals in our JS code
	if len(v.objects) == 0 {
		return
	}

	o := v.objects[0]
	m := make(map[string]interface{})

	// Decode object expression into map
	if err := (&decoder{}).Decode(o, &m); err != nil {
		log.Fatal("err while decoding object expression: ", o.JS())
	}

	fmt.Println("Decoded:", m)
}
```

**Comment by karelorigin** [comment]
I've had some sleep and I thought to myself that it actually doesn't make much sense to stringify the object expression as it's already a parsed structure in itself. I created this AST walker that will traverse the tree and decode the values into a map:

```golang
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"strconv"

	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/parse/v2/js"
)

// visitor is a AST visitor and collects all object expressions
type visitor struct {
	objects []*js.ObjectExpr
}

func (v *visitor) Enter(n js.INode) js.IVisitor {
	switch n := n.(type) {
	case *js.ObjectExpr:
		v.objects = append(v.objects, n)
	default:
		return v
	}

	// Automatically skip any nested nodes as we
	// already found our object expression
	return nil
}

func (v *visitor) Exit(n js.INode) {}

// decoder is a JSON decoder that turns an object expression node into valid JSON
type decoder struct {
	out map[string]interface{}
}

// Decode decodes an object expression
func (d *decoder) Decode(o *js.ObjectExpr) (map[string]interface{}, error) {
	d.out = make(map[string]interface{})

	// Walk through AST and decode values
	js.Walk(d, o)

	return d.out, nil
}

// value decodes a value belonging to a js.Property
func (d *decoder) value(expr js.IExpr) interface{} {
	// These should cover most scenarios but might not be complete
	// adding additional cases to the switch should be doable
	switch n := expr.(type) {
	case *js.LiteralExpr:
		return d.literal(n)
	case *js.ObjectExpr:
		return d.object(n)
	case *js.ArrayExpr:
		return d.array(n)
	}

	return nil
}

// literal decodes a literal expression
func (d *decoder) literal(expr *js.LiteralExpr) interface{} {
	// These should cover most scenarios but might not be complete
	// adding additional cases to the switch should be doable
	switch expr.TokenType {
	case js.StringToken:
		return d.str(expr)
	case js.DecimalToken:
		return d.decimal(expr)
	}

	return nil
}

// str decodes a string expression
func (d *decoder) str(expr *js.LiteralExpr) interface{} {
	return string(expr.Data)
}

// decimal decodes a decimal expression
func (d *decoder) decimal(expr *js.LiteralExpr) interface{} {
	i, err := strconv.Atoi(string(expr.Data))
	if err != nil {
		return nil
	}

	return i
}

// object decodes an object expression
func (d *decoder) object(expr *js.ObjectExpr) interface{} {
	m, err := (&decoder{}).Decode(expr)
	if err != nil {
		return nil
	}

	return m
}

// array decodes an array expression
func (d *decoder) array(expr *js.ArrayExpr) interface{} {
	array := make([]interface{}, len(expr.List))

	for i, elem := range expr.List {
		array[i] = d.value(elem.Value)
	}

	return array
}

func (d *decoder) Enter(n js.INode) js.IVisitor {
	switch n := n.(type) {
	case *js.Property:
		d.out[n.Name.String()] = d.value(n.Value)
	default:
		return d
	}

	// Automatically skip any node that was handled by the switch
	return nil
}

func (d *decoder) Exit(n js.INode) {}

func main() {
	ast, err := js.Parse(parse.NewInputString(`y = {"year": 2021, "days": [20, 21]};`))
	if err != nil {
		log.Fatal(err)
	}

	// Collect all object expressions from our JS code
	v := &visitor{}
	js.Walk(v, ast)

	// Skip if there weren't any object literals in our JS code
	if len(v.objects) == 0 {
		return
	}

	o := v.objects[0]

	// Decode object expression into map
	m, err := (&decoder{}).Decode(o)
	if err != nil {
		log.Fatal("err while decoding object expression:", o.JS())
	}

	fmt.Println("Decoded:", m)

	// Serialize to JSON
	b, err := json.Marshal(m)
	if err != nil {
		log.Fatal("err while serializing map:", err)
	}

	fmt.Println("JSON:", string(b))
}

```

Go playground: https://play.golang.org/p/A_vyDk5ZyOH

As you can see, you can always serialize it to JSON or map it to a struct using [mapstructure](https://github.com/mitchellh/mapstructure) if necessary. This way you don't have to deal with quotes or any other inconsistencies that may occur.

**Comment by 89z** [comment]
Sorry for late reply, I am also working on an HTML decoder based on this package [1].

> However, I did take a look at what the cause of this behavior might be, as it can create issues with property names that are invalid when not encapsulated by quotes: `{"1a": 1}` vs `{1a: 1}`.

Oh, good point, I didnt think about keys that must be quoted. That seems to reveal another problem: currently it doesnt seem possible to get the unquoted property name:

~~~
package main

import (
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

type quote struct{}

func (q quote) Enter(n js.INode) js.IVisitor {
   pName, ok := n.(*js.PropertyName)
   if ok {
      fmt.Println(pName)
      fmt.Println(pName.JS())
      fmt.Println(pName.Literal)
      fmt.Println(pName.Literal.JS())
      fmt.Println(pName.Computed)
   }
   return q
}

func (quote) Exit(js.INode) {}

func main() {
   ast, err := js.Parse(parse.NewInputString(`d={"month":12,"1day":31}`))
   if err != nil {
      panic(err)
   }
   for _, iStmt := range ast.BlockStmt.List {
      var q quote
      js.Walk(q, iStmt)
   }
}
~~~

Result:

~~~
month
month
month
month
<nil>
"1day"
"1day"
"1day"
"1day"
<nil>
~~~

I guess I could just do a `strings.Trim` or similar, unless you have a better option?

1. <https://github.com/89z/mech/blob/968f77ef/research/html_decode/html_decode.go>

**Comment by 89z** [comment]
Also @karelorigin, I had trouble with both your examples. Using this valid JavaScript input:

~~~go
const input = `d={ab:9,'cd':9,'c"d':9,"ef":9,"e'f":9}`
~~~

with the first example I get this:

~~~
err while decoding object expression
~~~

with the second example I get this:

~~~
ab
cd
'c"d'
ef
"e'f"
~~~

surrounding quotes should never be in the decoded output, as they are not actually part of the property name, but merely an escape mechanism. Proper decoded output should be:

~~~
ab
cd
c"d
ef
e'f
~~~

then, after that if someone were to JSON marshal, youd only have a single pair of surrounding double quotes for each, as expected.

**Comment by tdewolff** [comment]
I agree with @karelorigin here in that `JS()` is supposed to give the correct JS representation, not always the original one. The value of a key in an object is one of three things: an identifier, a string, or a numeric value (see https://tc39.es/ecma262/#prod-LiteralPropertyName). An identifier is equal to it's quoted value as a string, see the documentation at https://tc39.es/ecma262/#sec-object-initializer-runtime-semantics-evaluation. For JSON the key must always be a string, so you just need to add quotes for identifiers and numeric values (additionally you need to convert single quotes to double quotes for strings). I don't think this is a bug in the parser nor in the output of `JS()`, though we could obviously add a `JSON()` function to `ObjectLiteral` and `ArrayLiteral`.

**Comment by 89z** [comment]
> I don't think this is a bug in the parser nor in the output of `JS()`, though we could obviously add a `JSON()` function to `ObjectLiteral` and `ArrayLiteral`.

well said, thanks @tdewolff. Essentially what I am trying to do is turn some JavaScript like this:

~~~
ab = 'north';
cd = 'south';
~~~

into Go map like this:

~~~
map[string]string{"ab": "north", "cd": "south"}
~~~

where the keys are the variable names, and the values are JSON string representations of whatever the value may be (number, string, array, object). So a `JSON()` method would definitely help with that.

**Comment by karelorigin** [comment]
> const input = \`d={ab:9,'cd':9,'c"d':9,"ef":9,"e'f":9}\` 

Does not contain any object expressions so it actually does not return anything @89z, perhaps you meant:
```javascript
const input = d = {ab:9,'cd':9,'c"d':9,"ef":9,"e'f":9}
```

The additional quotes you received in your output are set by the parser, not the JS conversion functionality. I'm not sure what the reason for that was but I'm sure @tdewolff can tell us more. Keep in mind that attempting to parse JavaScript objects as JSON is actually not desirable as they are different in some ways, e.g. valid JSON does not accept single quotes and does not support expressions.

Perhaps I misunderstood the original problem but it looks like you are trying to do something different now. Everything you mentioned appears to be solvable using an AST walker, such as the one I gave earlier. I'm not really sure if a `JSON` methods fits within the purpose of this repository, I would recommend an example directory perhaps that showcases how to use walkers to tackle the issue.

**Comment by 89z** [comment]
> I agree with @karelorigin here in that `JS()` is supposed to give the correct JS representation, not always the original one.

@tdewolff but heres the issue: between `JS()` and `String()`, **one** of them should at least be able to give the input as given, and currently both just do the same thing. Take this program:

~~~go
package main

import (
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

func main() {
   ast, err := js.Parse(parse.NewInputString(`d={"month":12,"day":31}`))
   if err != nil {
      panic(err)
   }
   for _, iStmt := range ast.BlockStmt.List {
      fmt.Println(iStmt)
      fmt.Println(iStmt.JS())
   }
}
~~~

For my use case, the object is already valid JSON, so I dont need to transform it at all, I just need to output the object as is. But from what I can tell, neither function allows me to do that, they both strip the PropertyName quotes:

~~~
Stmt(d={month: 12, day: 31})
d = {month: 12, day: 31}
~~~

resulting in invalid JSON. So I think the `JS()` behavior is fine, but I dont think `String()` should just essentially repeat what `JS()` is doing.

> > const input = `d={ab:9,'cd':9,'c"d':9,"ef":9,"e'f":9}`
> 
> Does not contain any object expressions so it actually does not return anything @89z, perhaps you meant:

@karelorigin sorry I was not clear, that code I put was **Go** code, with the string containing JavaScript code.

> The additional quotes you received in your output are set by the parser, not the JS conversion functionality.

See heres the trouble though, as per my comments above, sometimes the quotes are getting stripped when I dont want them to be, then other time the quotes are not getting stripped when I do want them to be.

> I'm not sure what the reason for that was but I'm sure @tdewolff can tell us more. Keep in mind that attempting to parse JavaScript objects as JSON is actually not desirable as they are different in some ways, e.g. valid JSON does not accept single quotes and does not support expressions.

In general I agree with this, but in my case I am certain that the JavaScript objects are not only valid JSON, but are even formatted as such in the JavaScript code (all keys are double quoted).

> Perhaps I misunderstood the original problem but it looks like you are trying to do something different now.

My use case is, I have some JavaScript code, where JavaScript variables are being set to different values (objects, arrays, strings, numbers), but the values are always properly JSON encoded, so essentially I just want to extract the variable names as strings, and the values as JSON encoded strings (which they already are).

> I'm not really sure if a `JSON` methods fits within the purpose of this repository, I would recommend an example directory perhaps that showcases how to use walkers to tackle the issue.

I agree with this. I think an example directory would be a good start, then as need arises changes or additions could be made to the API. However I still think I have a valid concern about the basically identical output of `String()` and `JS()`, as detailed above.

**Comment by tdewolff** [comment]
> @tdewolff but heres the issue: between JS() and String(), one of them should at least be able to give the input as given, and currently both just do the same thing. Take this program:

This is actually not their purpose. `JS()` should return valid JavaScript (not JSON), and `String()` should just be _a_ string representation of the AST, not according to any specification. The AST does not keep the original JS, it just contains a syntax tree that is equivalent to the given code's syntax tree. The keys are quoted when they HAVE to be quoted, and unquoted if permitted. For JSON the key must always be a string, so you just need to add quotes for identifiers and numeric values (additionally you need to convert single quotes to double quotes for strings). A `JSON()` function may be out-of-scope for the library, but it would be fairly little code to implement.

**Comment by 89z** [comment]
> For JSON the key must always be a string, so you just need to add quotes for identifiers and numeric values (additionally you need to convert single quotes to double quotes for strings). A `JSON()` function may be out-of-scope for the library, but it would be fairly little code to implement.

I think this does it:

~~~go
package quote

import (
   "bytes"
   "github.com/tdewolff/parse/v2/js"
   "strconv"
)

type quote struct{}

func (q quote) Enter(n js.INode) js.IVisitor {
   pName, ok := n.(*js.PropertyName)
   if ok {
      b := bytes.Trim(pName.Literal.Data, `'"`)
      pName.Literal.Data = strconv.AppendQuote(nil, string(b))
   }
   return q
}

func (quote) Exit(js.INode) {}
~~~

but if anyone has a better option, I would be open to it. Thanks again for all the responses.

**Comment by 89z** [comment]
I think I found a better option. Instead of using the Parser, I can just use the Lexer. That way, the input stays as is. As long as what I said holds true, about the values being valid JSON, it seems to do the trick. I probably need to add more cases, but the example below works with basic inputs:

~~~js
package js

import (
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

type values map[string][]byte

func newValues(b []byte) values {
   var key string
   val := make(values)
   l := js.NewLexer(parse.NewInputBytes(b))
   for {
      switch tt, data := l.Next(); tt {
      case js.IdentifierToken:
         key = string(data)
      case js.CloseBraceToken, js.ColonToken, js.CommaToken, js.DecimalToken,
      js.OpenBraceToken, js.StringToken:
         val[key] = append(val[key], data...)
      case js.ErrorToken:
         return val
      }
   }
}
~~~

**Comment by 89z** [comment]
I ran into some more complicated JavaScript, I put my updated code below. One thing I realized is that RegExp literals can appear almost anywhere in the code, so Im not sure what the best way is to deal with that. For my code, if I see a slash, I try to parse as RegExp, then if that fails I back up and let it parse as slash literal. If anyone has better option let me know.

~~~go
package js

import (
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

type Lexer struct {
   *js.Lexer
   *parse.Input
}

func (l Lexer) Values() map[string][]byte {
   vals := make(map[string][]byte)
   for {
      var k string
      var ident bool
      for {
         if tt, data := l.Next(); tt == js.ErrorToken {
            return vals
         } else if tt == js.EqToken {
            break
         } else if tt == js.IdentifierToken || tt == js.DotToken {
            if ident {
               k += string(data)
            } else {
               k = string(data)
               ident = true
            }
         } else {
            ident = false
         }
      }
      for {
         tt, data := l.Next()
         if tt == js.SemicolonToken {
            break
         } else if tt == js.WhitespaceToken {
            continue
         } else if tt == js.DivToken {
            if tt, data = l.RegExp(); tt == js.ErrorToken {
               l.Rewind(0)
               tt, data = l.Next()
            }
         }
         vals[k] = append(vals[k], data...)
      }
   }
}
~~~

**Comment by tdewolff** [comment]
I've added the `JSON()` method! Please let me know if it works for you

**Comment by 89z** [comment]
Hm, that sounds good! are you going to push a new release, or do I need to try it off master?

**Comment by tdewolff** [comment]
There you go, I got v2.5.20 out!

**Comment by 89z** [comment]
Seems to work! This code produces expected result. Thanks again!

~~~go
package json

import (
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

type values map[string]string

func newValues(data string) (values, error) {
   ast, err := js.Parse(parse.NewInputString(data))
   if err != nil {
      return nil, err
   }
   v := make(values)
   for _, iStmt := range ast.BlockStmt.List {
      eStmt, ok := iStmt.(*js.ExprStmt)
      if ok {
         bExpr, ok := eStmt.Value.(*js.BinaryExpr)
         if ok {
            y, err := bExpr.Y.JSON()
            if err != nil {
               return nil, err
            }
            v[bExpr.X.JS()] = y
         }
      }
   }
   return v, nil
}
~~~
