### ISSUE TITLE
export const { name1, internal: name2 } = obj AST representation

### ISSUE THREAD

**Issue by blixt** [tdewolff/parse#83]
The representation of `export const { a: name1, b: name2 }` etc is currently represented as `*js.BindingObject` which implies certain features such as `...restProps` etc. In the spec there's a special definition for the export "object" declaration: https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-exports

Maybe it would make sense for the AST to also have a special node type for this?

I ran into this traversing various kinds of exports and the logic gets a bit tricky when there are more theoretical possibilities than actual valid JS spec possibilities.

**Comment by blixt** [comment]
So here's what I got trying to get a list of names exported by a module, iterating its top-level statements and running this function:

```go
func getExportNames(stmt *js.ExportStmt) (names []string, exportsAll bool) {
	if stmt == nil {
		return
	}
	if stmt.Default {
		names = append(names, "default")
		return
	}
	for _, alias := range stmt.List {
		if string(alias.Binding) == "*" {
			exportsAll = true
			continue
		}
		names = append(names, string(alias.Binding))
	}
	switch decl := stmt.Decl.(type) {
	case *js.VarDecl:
		for _, elem := range decl.List {
			switch binding := elem.Binding.(type) {
			case *js.Var:
				names = append(names, string(binding.Data))
			case *js.BindingObject:
				// We're ignoring the Rest property here because it's not possible in exports.
				for _, item := range binding.List {
					v, ok := item.Value.Binding.(*js.Var)
					if !ok {
						// Shouldn't happen in practice.
						continue
					}
					names = append(names, string(v.Name()))
				}
			}
		}
	case *js.FuncDecl:
		names = append(names, string(decl.Name.Name()))
	case *js.ClassDecl:
		names = append(names, string(decl.Name.Name()))
	}
	return
}
```

As you can see it gets a bit hairy with exceptions and assumptions for `*js.BindingObject` which is why I created this issue.

**Comment by tdewolff** [comment]
Are you sure it is a `*js.BindingObject`? From what I see is that the `ExportStatement` contains `List []Alias`, representing the `export {name as alias, more}` type of syntax you mention. Maybe I'm missing something?

**Comment by blixt** [comment]
Yup, it occurs in one of the types of export statements. I copied all of the examples from MDN into this playground with my utility function + debug output so you should be able to find it quickly:
https://play.golang.org/p/0snrm2v8GX0

Try running it and you'll see the all-caps message for one of the statements.

**Comment by blixt** [comment]
Ah I realized my example in the title was wrong, this only happens for `export { a: b } = obj` and not `export { a as b }`.

**Comment by blixt** [comment]
Alright so I think I just completely misunderstood the limitations of this kind of export. As far as I can tell it *does* allow rest properties and now I think I misread the spec. This works fine:

```javascript
const js = `const o = { a: 42, b: "hello" }; export const { a: test, ...rest } = o;`
const url = await URL.createObjectURL(new Blob([js], { type: "text/javascript" }))
const module = await import(url)
console.log(module.test, module.rest) // 42 { b: "hello" }
```

I think I just have to actually convert the binding into individual variables that are exported in my utility. Feel free to close this issue if you don't think there's anything to be done to help this – export syntax probably just really is this complicated. :)

**Comment by blixt** [comment]
Okay I think after more testing I've come to the conclusion that the way it works now is the only way it should work. Basically, something like this should work fine and export the names `a`, `c`, `d`, `f`, `g`, `h`, `i`, `k`, `l`, `m`, and `n`.

```javascript
export var { a: { b: c, ...d }, e: [f, g, { h, i, j: k, ...l }, ...m], ...n } = o;
```

**Comment by tdewolff** [comment]
Great, thanks for verifying, I'm happy we now know it's working well :-)

**Comment by blixt** [comment]
Here's the code that behaves as expected based on the above findings if anyone ever runs into this and wants to figure out how to get a complete list of exported names from a JS module:

https://play.golang.org/p/cJUbIuCx4ug
