### ISSUE TITLE
html: Text method empty in some cases

### ISSUE THREAD

**Issue by 89z** [tdewolff/parse#84]
Using this program:

~~~go
package main

import (
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/html"
)

const s = `<script>var x = 'lorem ipsum';</script>
<span class='user'>John Doe</span>`

func main() {
   l := html.NewLexer(parse.NewInputString(s))
   for {
      tt, data := l.Next()
      if tt == html.ErrorToken {
         break
      }
      fmt.Printf("%v %q %q\n", tt, data, l.Text())
   }
}
~~~

I get this result:

~~~go
StartTag "<script" "script"
StartTagClose ">" ""
Text "var x = 'lorem ipsum';" ""
EndTag "</script>" "script"
Text "\n" "\n"
StartTag "<span" "span"
Attribute " class='user'" "class"
StartTagClose ">" ""
Text "John Doe" "John Doe"
EndTag "</span>" "span"
~~~

so the `Text` method is not returning anything with the `script` element, but it is returning something with the `span` element. That seems unexpected to me, and also inconvenient, as anyone wrapping the `Lexer` type will need to add a `struct` field to maintain the state, as `Text` method would be unreliable.

**Comment by 89z** [comment]
I came up with a workaround:

~~~go
func (l lexer) bytes() []byte {
   for {
      switch tt, data := l.Next(); tt {
      case html.ErrorToken:
         return nil
      case
      html.TextToken,
      html.EndTagToken,
      html.StartTagVoidToken,
      html.StartTagToken:
         return data
      }
   }
}
~~~

**Comment by tdewolff** [comment]
Not sure I follow, it seems that for the script element it does return
something for text right? Can you be more clear in what result you expected
instead?

**Comment by 89z** [comment]
In the original example `Next` returns the content from `script`, but `Text` returns nothing. In my case I didnt end up needing the method anyway, but it might be worth looking at.

**Comment by tdewolff** [comment]
I see now, should be fixed!

**Comment by 89z** [comment]
@tdewolff thanks, you are awesome man!
