### ISSUE TITLE
JSON method causes "b" output in some cases

### ISSUE THREAD

**Issue by 89z** [tdewolff/parse#86]
For some reason, running this program:

~~~go
package main

import (
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
)

type visit struct{}

func (visit) Exit(js.INode) {}

func (v visit) Enter(n js.INode) js.IVisitor {
   n.JSON()
   return v
}

func main() {
   ast, err := js.Parse(parse.NewInputString("var x = {y: 5 > 2}"))
   if err != nil {
      panic(err)
   }
   var vis visit
   js.Walk(vis, ast)
}
~~~

Produces this output:

~~~
b
b
~~~

I am not sure why its outputting `b`, as I do not have any print statements in the program.

**Comment by 89z** [comment]
Looks like the issue is here:

https://github.com/tdewolff/parse/blob/92ee1b3342221fc0d72623f8c224c2947d162cd8/js/ast.go#L1752-L1756

**Comment by tdewolff** [comment]
A debugging artefact, thanks!
