### ISSUE TITLE
Wrong handling of JS numeric separators in some circumstances

### ISSUE THREAD

**Issue by curio77** [tdewolff/parse#96]
Minify turns `5_000` (JavaScript) into `5_e3`, which is invalid (Chrome says: `Uncaught SyntaxError: Numeric separators are not allowed at the end of numeric literals`).

**Comment by tdewolff** [comment]
This was fixed recently in https://github.com/tdewolff/minify/commit/f8ec698904204fe0b4c5c60b2e216e07da920c06 and will be out in a release soon!
