### ISSUE TITLE
v2.5.33 backwards-breaks packages depending on it, including current github.com/tdewolff/minify/v2

### ISSUE THREAD

**Issue by samplex14** [tdewolff/parse#97]
The latest release removed OptChainExpr which is required by most recent versions of github.com/tdewolff/minify
Just running `go get -u` in any project using the js minifer breaks the project with ambiguous messages like `github.com/tdewolff/minify/v2@v2.11.7/js/js.go:1203:11: undefined: js.OptChainExpr` - which is *really* obnoxious to debug because the error comes from a package named `js` but it refers to `parse/v2/js` and not it's origin `minify/v2/js`.

To clarify: The issue stated above is an example of the symptom of the problem, the core problem being that you can't drop api elements in a minor release in semantic versioning - backwards-incompatible changes requires a major release.

Go uses semantic versioning for modules, which comes with certain expectations (eg minor/patch releases are always backwards-compatible and can always be upgraded unconditionally), see here: https://semver.org/

**Comment by tdewolff** [comment]
Ah yeah keep forgetting that. The new release of `minify` should fix this.

**Comment by samplex14** [comment]
I dont think that's the best option here - what about people that were using `github.com/tdewolff/parse/v2` and depend on `OptChainExpr` in their code? They would have to use v2.5.32 and can never run update their dependencies anymore because go doesnt allow fixing minor verison numbers (since there is no need for that in semantic versioning). 

The go toolchain has a solution for this exact problem: revert the release (see https://play-with-go.dev/retract-module-versions_go116_en/), mark `OptCharExpr` as *deprecated* using a deprecation doc comment and delay removing it until v3.0.0.
