### ISSUE TITLE
js parser accepts a single backtick as valid js

### ISSUE THREAD

**Issue by Adjective-Object** [tdewolff/parse#98]
I would expect this to error, as it contains an unterminated string template literal. 

```go
ast, parseErr := js.Parse(parse.NewInputString("`"), js.Options{})
```

When run via node, it fails to parse
```
$ node
> eval('`')
Uncaught SyntaxError: Unexpected end of input
```

This was replicated against github.com/tdewolff/parse/v2 v2.5.29

If you can point me in the right direction, I can take a stab at fixing this!

**Comment by tdewolff** [comment]
Thanks Max, and thanks for offering to fix it! I've actually already gone ahead and fixed it, including a better error message for unterminated string.
